[package]
name = "slint-rust-template"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.8.0"
deconz = { path = "../deconz"}
tokio = { version = "1.45.1", features = ["macros", "rt", "rt-multi-thread"] }

[build-dependencies]
slint-build = "1.8.0"
